name: GitHub Actions Demo

on:
  push:
    branches:
      - main
      - demo-branch
  workflow_dispatch:
    inputs:
      loglevel:
        type: choice
        options:
          - info
          - warning
          - debug
        default: info
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo "Hello this is a workflow template running log level ${{ github.event.inputs.logLevel }}" 
